# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('judgement_date', models.DateField()),
                ('mentioned_in', models.ManyToManyField(related_name='_case_mentioned_in_+', to='case.Case')),
                ('mentiones', models.ManyToManyField(related_name='_case_mentiones_+', to='case.Case')),
            ],
        ),
    ]
